[package]
name = "db"
version = "0.1.0"
edition = "2021"

[features]
default = ["postgres-tls"]
postgres-tls = ["dep:postgres-native-tls", "dep:native-tls"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
hex.workspace = true
gpui.workspace = true
gpui-component.workspace = true
chrono.workspace = true
tokio-postgres.workspace = true
postgres-native-tls = { workspace = true, optional = true }
native-tls = { workspace = true, optional = true }
tokio-util = { workspace = true, features = ["compat"] }
one-core.workspace = true
sqlformat.workspace = true
sqlparser.workspace = true
uuid.workspace = true
dashmap.workspace = true
moka.workspace = true
smol.workspace = true
regex.workspace = true
thiserror.workspace = true
rust-i18n.workspace = true
[dev-dependencies]
proptest = { workspace = true }
tempfile = "3"
